### ISSUE TITLE
Problema em executar 'make build-analytics'

### ISSUE THREAD

**Issue by emmenezes** [BOSS-BigOpenSourceSister/rasa-ptbr-boilerplate#12]
Ao tentar fazer o comando 'make build-analytics', o comando não termina de executar por conta de um link que parece estar fora do ar.
O link é [https://centos7.iuscommunity.org/ius-release.rpm](https://centos7.iuscommunity.org/ius-release.rpm)

![image](https://user-images.githubusercontent.com/27732593/93539486-58f95f00-f927-11ea-81b1-34e6514416a8.png)

**Comment by emmenezes** [comment]
Atualização:

Eu fiz uma alteração no kibana.Dockerfile para o pacote binário da versão mais recente no site [pkgs.org](https://centos.pkgs.org/7/ius-x86_64/apr15u-1.5.2-2.ius.centos7.x86_64.rpm.html) e o programa conseguiu passar dessa parte

Antes:
RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm

Depois:
RUN yum -y install https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/apr15u-1.5.2-2.ius.centos7.x86_64.rpm

Agora estou enfrentando outro problema com a linha:
RUN yum -y install python36u

![image](https://user-images.githubusercontent.com/27732593/93542157-adeca380-f92e-11ea-9189-caed20922cb9.png)

**Comment by emmenezes** [comment]
Esse segundo problema era relacionado à instalação do Python. Tentei fazer a mesmo alteração que fiz para IUS, mas não deu certo então eu mudei novamente o link de instalação da IUS no kibana.DockerFile e assim consegui executar toda build. 
Agora tenho um problema para executar o firefox, pois o programa exige autorização de administrador, mas estou com receio, porque vi que era um procedimento que pode trazer riscos ao usuário. Estou procurando outras formas de resolver isso.

Antes:
RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm

Depois:
RUN yum -y install https://repo.ius.io/ius-release-el7.rpm

Imagem do novo erro:
![image](https://user-images.githubusercontent.com/27732593/93666128-edf87700-fa51-11ea-9f20-e55a16efec80.png)

**Comment by BrunaNayara** [comment]
@emmenezes No primeiro passo que deu errado, eu alterei na mesma linha que você alterou, mas coloquei aasim:

```
RUN yum install -y https://repo.ius.io/ius-release-el7.rpm
``` 
E ao final do comando ele já abriu essa página do kibana (http://localhost:5601/app/kibana#/home?_g=())

![image](https://user-images.githubusercontent.com/4125846/93688253-d72a4280-fa9a-11ea-9d8e-e606875fbb3a.png)
