### ISSUE TITLE
Criar uma nova custom action (Maria Vitória e Brenda)

### ISSUE THREAD

**Issue by clarissalimab** [BOSS-BigOpenSourceSister/rasa-ptbr-boilerplate#15]
# Problema
Criar uma nova custom action acessando uma API, sugestão de API nos slides.
Bônus: criar uma intent utilizando slot.

# Sugestão de solução
Fala um pouco o que seria uma boa solução (não necessariamente tecnicamente)

## Tarefas
- [ ] Alguns passos para a solução 
- [ ] Critério de aceitação etc

**Comment by clarissalimab** [comment]
Recursos:
* [Vídeo do conteúdo da semana](https://www.youtube.com/watch?v=XeQqW6gmU8U)
* [Tutorial Custom Actions - Parte 1](https://www.youtube.com/watch?v=JMlpmQoDCU4)
* [Tutorial Custom Actions - Parte 2](https://www.youtube.com/watch?v=oyoJW7LKvmE)
* [Slides](https://docs.google.com/presentation/d/1o2mseEX3mPOK-8YGtzrvxosmhNquR8uya-eMKvE7H6c/edit?usp=sharing)

**Comment by BrunaNayara** [comment]
PR dessa issue #20
