### ISSUE TITLE
Criar uma nova custom action (Esther e Eduarda)

### ISSUE THREAD

**Issue by clarissalimab** [BOSS-BigOpenSourceSister/rasa-ptbr-boilerplate#16]
# Problema
Criar uma nova custom action acessando uma API, sugestão de API nos slides.
Bônus: criar uma intent utilizando slot.

# Sugestão de solução
Fala um pouco o que seria uma boa solução (não necessariamente tecnicamente)

## Tarefas
- [ ] Alguns passos para a solução 
- [ ] Critério de aceitação etc

**Comment by clarissalimab** [comment]
Recursos:
* [Vídeo do conteúdo da semana](https://www.youtube.com/watch?v=XeQqW6gmU8U)
* [Tutorial Custom Actions - Parte 1](https://www.youtube.com/watch?v=JMlpmQoDCU4)
* [Tutorial Custom Actions - Parte 2](https://www.youtube.com/watch?v=oyoJW7LKvmE)
* [Slides](https://docs.google.com/presentation/d/1o2mseEX3mPOK-8YGtzrvxosmhNquR8uya-eMKvE7H6c/edit?usp=sharing)

**Comment by emmenezes** [comment]
# Tarefas
## Objetivo: A partir de cidade e estado disponibilizado pela usuária, o bot retorna com restaurantes da região.

### Sem validação de dados (para teste):

- [ ] Criar intents para chamar o serviço da API
- [ ] Declarar no domain.yml a intent, a entidade (se usada) e a utter
- [ ] Criar slot para cidade e estado
- [ ] Criar action que usa dados dos slots com a API foursquare

### Com validação de dados (lida com divergências):

- [ ] Criar form 
- [ ] Associar form com Action

### Exemplo de chamada de api sem validação de dados:

foursquare manaus am
interpretação: foursquare (chama serviço) manaus (entidade: cidade) am (entidade: estado)

**Comment by clarissalimab** [comment]
Dá gosto de ver uma issue bem descrita assim! Mandaram muito bem. Gostei que vocês resolveram tornar mais desafiador ainda usando o form em vez de só o slot. Curiosa para ver o resultado :sparkles:
