### ISSUE TITLE
Sugestão para execução do BoilerPlate

### ISSUE THREAD

**Issue by emmenezes** [BOSS-BigOpenSourceSister/rasa-ptbr-boilerplate#4]
Com @giovanadionisio

**Problema**
Ao executar os comando para executar o docker, ocorre erro de permissão.

**Solução desejada**
Adicionar ao tutorial os comandos ‘sudo docker ps’ e ‘sudo make run-shell’ em caso de erro.

**Comment by clarissalimab** [comment]
Em qual ambiente isso aconteceu? (Ubuntu?)

**Comment by emmenezes** [comment]
Isso, Ubuntu

**Comment by BrunaNayara** [comment]
@emmenezes você ainda tá com esse problema?
Pode colocar prints aqui pra gente tentar resolver?

**Comment by emmenezes** [comment]
No caso, esse problema ocorreu com a @giovanadionisio, quando eu fiz no meu próprio, só precisei dar sudo na primeira vez, agora roda normalmente sem. Giovana, o seu agora funciona sem sudo?

**Comment by BrunaNayara** [comment]
Beleza. Obrigada @emmenezes.

**Comment by giovanadionisio** [comment]
> No caso, esse problema ocorreu com a @giovanadionisio, quando eu fiz no meu próprio, só precisei dar sudo na primeira vez, agora roda normalmente sem. Giovana, o seu agora funciona sem sudo?

não, ainda preciso do sudo sempre

**Comment by BrunaNayara** [comment]
Ah, o `sudo` você vai sempre precisar se você não colocar o docker dentro do grupo de usuários do computador. Mas isso é uma configuração do docker. Se você quiser não precisar disso, é só seguir esse [tutorial aqui](https://docs.docker.com/engine/install/linux-postinstall/). Se você não quiser adicionar não precisa, só lembrar de usar o `sudo` quando pedir :smile: 

Eu não adiciono, então sempre preciso usar sudo quando vou dar algum comando do docker (que está dentro do make, por exemplo).
Se depois você quiser entender um pouco melhor sobre isso, pode me perguntar :smile_cat: 


cc @giovanadionisio
